---
title: "Tentative Topics Schedule"
subtitle: "Spring 2023 - University of Portland"
---

<br>

<center>**- See Books & Online Resources List for the reading materials -**</center>

<center>[**The readings are not mandatory but it is encouraged.**]{style="color:red"}</center>

<center>[**Lecture slides will be available after class.**]{style="color:red"}</center>

<br>

The "[\*]" column in the table below contains a number on which it refers to a numbered item in the Books & Online Resources List. For example "[CV2]" refers to the first item in the list, which is our main text book titled "Calculus Volume 2".

<br>

## **Topics and Reading Materials**

<br>

| **Week** | **Day** |                                                     **Topic**                                                     |     **[CV2]**     |  **Learning Target**   |             **WeBWork**              |        **Lab**        |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
|  **1**   | M 1/16  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|          | W 1/18  |                                            Orientation & Introduction                                             |     Syllabus      |           \-           |                  \-                  |          \-           |
|          | Th 1/19 |                                                   5.1 Sequences                                                   |      Ch. 5.1      |           \-           |                  \-                  |          \-           |
|          | F 1/20  |                                         5.1 Sequences Cont. & 5.2 Series                                          | Ch. 5.1 & Ch. 5.2 |           \-           |           Section 5.1 Due            |          \-           |
|  **2**   | M 1/23  |                                                 5.2 Series Cont.                                                  |      Ch. 5.2      |           \-           |                  \-                  |          \-           |
|          | W 1/25  |                                                 1.5 Substitution                                                  |      Ch. 1.5      |           \-           |           Section 5.2 Due            |          \-           |
|          | Th 1/26 |                                                    Assessment                                                     |        \-         |      SS1\*, SS2\*      |                  \-                  |          \-           |
|          | F 1/27  |                                              1.5 Substitution Cont.                                               |      Ch. 1.5      |           \-           |                  \-                  |          \-           |
|  **3**   | M 1/30  |                                              3.7 Improper Integrals                                               |      Ch. 3.7      |           \-           |                  \-                  |          \-           |
|          |  W 2/1  |                         3.7 Improper Integrals Cont.<br>&<br>Lab 1: Sequences and Series                          |      Ch. 3.7      |           \-           |  Section 1.5 Due & Section 3.7 Due   |      Lab 1 Open       |
|          | Th 2/2  |                                                    Assessment                                                     |        \-         |  SS1\* 2nd, SS2\* 2nd  |                  \-                  |          \-           |
|          |  F 2/3  |                                                 5.3 Integral Test                                                 |      Ch. 5.3      |           \-           |                  \-                  |          \-           |
|  **4**   |  M 2/6  |                                               5.4. Comparison Test                                                |      Ch. 5.4      |           \-           |           Section 5.3 Due            |          \-           |
|          |  W 2/8  |                                             5.4 Comparison Test Cont.                                             |        \-         |           \-           |                  \-                  |          \-           |
|          | Th 2/9  |                                                    Assessment                                                     |        \-         |      SS3, SS4, I5      |                  \-                  |          \-           |
|          | F 2/10  |                                            5.5 Alternating Series Test                                            |      Ch. 5.5      |           \-           |           Section 5.4 Due            |          \-           |
|  **5**   | M 2/13  |                                              5.6 Ratio and Root Test                                              |      Ch. 5.6      |           \-           |           Section 5.5 Due            |          \-           |
|          | W 2/15  |                           5.6 Ratio and Root Test Cont.<br>&<br>Lab 2: All Series Tests                           |        \-         |           \-           |           Section 5.6 Due            | Lab 1 Due, Lab 2 Open |
|          | Th 2/16 |                                                    Assessment                                                     |        \-         |        SS5, SS6        |                  \-                  |          \-           |
|          | F 2/17  |                                             3.1 Integration by Parts                                              |      Ch. 3.1      |           \-           |                  \-                  |          \-           |
|  **6**   | M 2/20  |                                          3.1 Integration by Parts Cont.                                           |        \-         |           \-           | Section 3.1 Due, All Series Test Due |          \-           |
|          | W 2/22  |                                            3.2 Trigonometric Integrals                                            |      Ch. 3.2      |           \-           |                  \-                  |          \-           |
|          | Th 2/23 |                                                    *Cancelled*                                                    |        \-         |           \-           |                  \-                  |          \-           |
|          | F 2/24  |                                                    *Cancelled*                                                    |        \-         |           \-           |                  \-                  |          \-           |
|  **7**   | M 2/27  | 3.2 Trigonometric Integrals Cont. (Asynchronous) |        \-         |           \-           |           Section 3.2 Due            |          \-           |
|          |  W 3/1  |                                   3.3 Trigonometric Substitution (Asynchronous)                                   |      Ch. 3.3      |           \-           |                  \-                  |       Lab 2 Due       |
|          | Th 3/2  |                                3.3 Trigonometric Substitution Cont.(Asynchronous)                                 |        \-         |           \-           |                  \-                  |          \-           |
|          |  F 3/3  |                                                    Assessment                                                     |        \-         |      SS7\*, I1\*       |           Section 3.3 Due            |          \-           |
|  **8**   |  M 3/6  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|          |  W 3/8  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|          | Th 3/9  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|          | F 3/10  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|  **9**   | M 3/13  |                                                                                                                   |                   |                        |                                      |                       |
|          | W 3/15  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 3/16 |                                                    Assessment                                                     |        \-         |      I2, I3, I4\*      |                  \-                  |          \-           |
|          | F 3/17  |                                                                                                                   |                   |                        |                                      |                       |
|  **10**  | M 3/20  |                                                                                                                   |                   |                        |                                      |                       |
|          | W 3/22  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 3/23 |                                                    Assessment                                                     |        \-         | PS1\*, PS2\*, I4\* 2nd |                  \-                  |          \-           |
|          | F 3/24  |                                                                                                                   |                   |                        |                                      |                       |
|  **11**  | M 3/27  |                                                                                                                   |                   |                        |                                      |                       |
|          | W 3/29  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 3/30 |                                                    Assessment                                                     |        \-         |    PS1\* 2nd, PS3\*    |                  \-                  |          \-           |
|          | F 3/31  |                                                                                                                   |                   |                        |                                      |                       |
|  **12**  |  M 4/3  |                                                                                                                   |                   |                        |                                      |                       |
|          |  W 4/5  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 4/6  |                                                                                                                   |        \-         |                        |                  \-                  |          \-           |
|          |  F 4/7  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|  **13**  | M 4/10  |                                                    *No Class*                                                     |        \-         |           \-           |                  \-                  |          \-           |
|          | W 4/12  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 4/13 |                                                    Assessment                                                     |                   |      A1, A2\*, A3      |                                      |                       |
|          | F 4/14  |                                                                                                                   |                   |                        |                                      |                       |
|  **14**  | M 4/17  |                                                                                                                   |                   |                        |                                      |                       |
|          | W 4/19  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 4/20 |                                                    Assessment                                                     |        \-         |    PP1\*, A2\* 2nd     |                  \-                  |          \-           |
|          | F 4/21  |                                                                                                                   |                   |                        |                                      |                       |
|  **15**  | M 4/24  |                                                                                                                   |                   |                        |                                      |                       |
|          | W 4/26  |                                                                                                                   |                   |                        |                                      |                       |
|          | Th 4/27 |                                                    Assessment                                                     |        \-         | PP1\* 2nd, PP2, PP3\*  |                  \-                  |          \-           |
|          | F 4/28  |                                                      Review                                                       |        \-         |           \-           |                  \-                  |          \-           |
|  **-**   | Th 5/4  |                                                    Final Exam                                                     |        \-         |           \-           |                  \-                  |          \-           |

<br>

## **Books & Online Resources Lists**

<br>

### Main Textbook

[CV2] [Herman, E., Strang, G., Radulovich, W., Rutter, E. A., Smith, D., Messer, K. R., ... & McCune, D. (2016). Calculus Volume 2.](https://openstax.org/books/calculus-volume-2/pages/preface){target="_blank"}

<br>
